//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TercerParcial_Centurion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagina
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CantidadLikes { get; set; }
        public string Categoria { get; set; }
        public string Ciudad { get; set; }
    }
}
